#!/bin/sh

set -e

# PATH TO YOUR HOSTS FILE
ETC_HOSTS=/etc/hosts

# DEFAULT IP FOR HOSTNAME
IP="127.0.0.1"

for HOSTNAME in "campsite.test" "app.campsite.test" "api.campsite.test" "auth.campsite.test" "admin.campsite.test"
do
    echo "> Adding $HOSTNAME to your etc/hosts file.";
    HOSTS_LINE="$IP\t$HOSTNAME"
    if [ -n "$(grep -wF "$HOSTNAME" /etc/hosts)" ]
    then
        echo "\033[1;32m $HOSTNAME already exists.\033[0m"
    else
        echo "Adding $HOSTNAME to your $ETC_HOSTS";
        sudo -- sh -c -e "echo '$HOSTS_LINE' >> /etc/hosts";

        if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
            then
                echo "$HOSTNAME was added successfully \n $(grep $HOSTNAME /etc/hosts)";
            else
                echo "Failed to Add $HOSTNAME, Try again!";
        fi
    fi
done
