#!/bin/sh

set -e

if [ "$1" = "--pristine" ]; then
	export SETUP_PRISTINE=1
fi

echo "\nInstalling bundler and gems...\n============================================================"
bundle install --local
echo "\033[1;32mGem files installed.\033[0m"

echo "\nInstalling javascript dependencies...\n============================================================"
yarn install
echo "\033[1;32mJavascript dependencies installed.\033[0m"

if [ -n "$SETUP_PRISTINE" ]; then
	echo "\nDropping existing databases...\n============================================================"
	mysql -u root -e 'DROP DATABASE IF EXISTS campsite_api_development; DROP DATABASE IF EXISTS campsite_api_test;'
fi

echo "\nChecking encryption keys...\n============================================================"
bin/rails dev:setup_credentials

echo "\nRunning redis-server in the background...\n============================================================"
brew services restart redis &

echo "\nSetting up database...\n============================================================"
brew services restart mysql@8.0
rails db:setup

echo "\nLoading time zones into database...\n============================================================"
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
brew services restart mysql@8.0

echo "\nShutting down redis-server...\n============================================================"
redis-cli shutdown

echo "\033[1;32mSetup completed!\033[0m"
