#!/bin/bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
source ~/.nvm/nvm.sh && nvm install && nvm use

brew install tmux overmind flyctl pnpm yarn

# Setup API
(cd api && script/setup)

# Setup Elasticsearch
docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.0
docker network create elastic
docker rm -f elasticsearch
docker create --name elasticsearch --net elastic -p 9200:9200 -e discovery.type=single-node -e ES_JAVA_OPTS="-Xms1g -Xmx1g" -e xpack.security.enabled=false -it docker.elastic.co/elasticsearch/elasticsearch:8.8.0

# Setup JS monorepo
pnpm install

# Setup screenshot service
(cd html-to-image && npm install)